version: "3.9"

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /var/www/html/vendor
      - ./:/var/www/html

  web:
    container_name: web
    image: nginx:stable-alpine3.17-slim
    ports:
      - "9081:80"
    volumes:
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/html

  mysqldb:
    container_name: mysqldb
    image: mysql:8.0
    ports:
        - "33066:3306"
    restart: unless-stopped
    environment:
        MYSQL_DATABASE: "${DB_DATABASE}"
        MYSQL_USER: "${DB_USERNAME}"
        MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
        MYSQL_PASSWORD: "${DB_PASSWORD}"
    volumes:
        - data:/var/lib/mysql

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    depends_on:
        - mysqldb
    environment:
        PMA_HOST: mysqldb
        PMA_PORT: 3306
        MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
    restart: unless-stopped
    ports:
        - "8081:80"

volumes:
    data:
