  name: CI workflow

  on:
    push:
      branches:
        - 'master'
      tags:
        - 'v*'
    pull_request:
      branches:
        - 'master'
  jobs:
    build:
      strategy:
        matrix:
          os: [ ubuntu-latest ]
          php-version: [ 8.1 ]
      runs-on: ${{ matrix.os }}
      defaults:
        run:
          working-directory: ./
      steps:
        - uses: actions/checkout@v3

        - name: Set up PHP
          uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
          with:
            php-version: ${{ matrix.php-version }}

        - name: Copy .env
          run: php -r "file_exists('.env') || copy('.env.example', '.env');"

        - name: Install dependencies
          run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

        - name: Generate key
          run: php artisan key:generate

        - name: Directory Permissions
          run: chmod -R 777 storage bootstrap/cache

        - name: Execute tests (Unit and Feature tests) via PHPUnit
          run: php artisan test

        - name: Docker Meta
          id: meta
          uses: docker/metadata-action@v4
          with:
            images: |
              tu1anh/docker-api-laravel
            tags: |
              type=raw,value=latest
              type=ref,event=branch
              type=ref,event=pr
              type=semver,pattern={{version}}
              type=semver,pattern={{major}}.{{minor}}

        - name: Login to Docker Hub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKER_HUB_USERNAME }}
            password: ${{ secrets.DOCKER_HUB_PASSWORD }}

        - name: Build and push
          uses: docker/build-push-action@v4
          with:
            file: ./Dockerfile
            context: .
            push: true
            tags: ${{ steps.meta.outputs.tags }}
