  name: Laravel Docker

  on:
    push:
      branches: [ master ]
    pull_request:
      branches: [ master ]

  jobs:
    build:
      runs-on: ubuntu-latest
      defaults:
        run:
          working-directory: ./

      strategy:
        matrix:
          php-version: [8.1]

      steps:
        - uses: actions/checkout@v3

        - name: Set up PHP
          uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
          with:
            php-version: ${{ matrix.php-version }}

        - name: Copy .env
          run: php -r "file_exists('.env') || copy('.env.example', '.env');"

        - name: Install dependencies
          run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

        - name: Generate key
          run: php artisan key:generate

        - name: Directory Permissions
          run: chmod -R 777 storage bootstrap/cache

        - name: Execute tests (Unit and Feature tests) via PHPUnit
          run: php artisan test

        - name: Build Docker Image
          run: docker build -t tu1anh/laravel-app:1.1 -f ./Dockerfile .
        - name: Login To Docker Hub
          run: docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
        - name: Push Docker Image
          run: docker push tu1anh/laravel-app:1.1
